version: "3.9"

services:

  # Bot API service
  bot-api:
    environment:
      TELEGRAM_WEB_APP_URL: https://${NGROK_DOMAIN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_PAYMENTS_TOKEN: ${TELEGRAM_PAYMENTS_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      DB_CONNECTION_STRING: postgres://guide:guide@postgres-db:5432/guide-system?sslmode=disable
      S3_CONNECTION_STRING: s3://guide:guide@s3-mock:7480/guide-objects?ssl=false
    restart: on-failure
    build:
      context: ./api

  # PostgreSQL DB
  postgres-db:
    image: postgres
    volumes:
      - guide-pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guide
      POSTGRES_PASSWORD: guide
      POSTGRES_DB: guide-system
    restart: on-failure

  # SQL migrations with go-migrate
  db-migrator:
    image: migrate/migrate
    command: -path=/migrations/ -database postgres://guide:guide@postgres-db:5432/guide-system?sslmode=disable up 
    volumes:
      - ./api/provider/db/migrations/postgres:/migrations
    restart: on-failure

  # UI for PostgreSQL DB
  postgres-admin:
    image: dpage/pgadmin4
    volumes:
      - guide-pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: on-failure
    ports:
      - 8100:80

  # Mocked S3 server
  s3-mock:
    image: quay.io/s3gw/s3gw
    volumes:
      - guide-s3:/data
    environment:
      RGW_DEFAULT_USER_ACCESS_KEY: guide
      RGW_DEFAULT_USER_SECRET_KEY: guide
    restart: on-failure

  # UI for S3 server
  s3-ui:
    image: quay.io/s3gw/s3gw-ui
    environment:
      S3GW_SERVICE_URL: http://s3-mock:7480
    restart: on-failure
    ports:
      - 8200:8080

  # Bot UI in development mode
  bot-ui:
    environment:
      REACT_APP_BOT_API_URL: https://${NGROK_DOMAIN}/api
    restart: on-failure
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/index.html:/app/index.html
      - ./ui/vite.config.js:/app/vite.config.js
    build:
      context: ./ui
      dockerfile: dev.dockerfile

  # Nginx proxy to forward request to UI and API
  dev-proxy:
    image: nginx:stable-alpine
    environment:
      PORT: 3000
      API_URL: http://bot-api:3000
      UI_URL: http://bot-ui:3000
    restart: on-failure
    volumes:
      - ./proxy.template:/etc/nginx/templates/default.conf.template

  # Ngrok service
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    restart: on-failure
    command: ["http", "--domain=${NGROK_DOMAIN}", "dev-proxy:3000", "--log=stdout"]

volumes:
  guide-s3:
  guide-pg-db:
  guide-pg-admin: